### ISSUE TITLE
Change 'master' to 'main'

### ISSUE THREAD

**Issue by AndrewManHayChiu** [RTO-Performance-Indicators/survey_analytics#34]
@mjrooney87 I think it's time we change the 'master' branch to 'main'. 

GitHub made this standard in November 2020, I think.

**Comment by mjrooney87** [comment]
Happy for you to do this. I hadn't even made the slavery connection but now it's bothering me haha

**Comment by AndrewManHayChiu** [comment]
Looks like it's easy to do, and maybe should be applied to all of our repos.

[See here](https://github.com/github/renaming)

**Comment by AndrewManHayChiu** [comment]
Done
